name: Build SunamoRss

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoRss
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoRss/SunamoRss.csproj

    - name: Build
      run: dotnet build SunamoRss/SunamoRss.csproj --configuration Release --no-restore

  test:
    name: Test SunamoRss.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoRss.Tests/SunamoRss.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoRss.Tests/SunamoRss.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoRss.Tests/SunamoRss.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
